# .github/workflows/add-secret-version.yml
name: add-secret-version
on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  add_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/608522675724/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account_email: github-actions-sa@project-sauter-hydro-forecast.iam.gserviceaccount.com

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: project-sauter-hydro-forecast

      - name: Add secret version
        env:
          SA_KEY_JSON: ${{ secrets.SA_ENA_KEY_JSON }}   # GitHub secret (base64 or raw)
        run: |
          echo "$SA_KEY_JSON" > sa-ena-pipeline-key.json
          gcloud secrets versions add sa-ena-pipeline-key --data-file=sa-ena-pipeline-key.json --project=project-sauter-hydro-forecast
